### ISSUE TITLE
Poetry is not installed on first time building databallpy from source

### ISSUE THREAD

**Issue by Swopper050** [Alek050/databallpy#130]
This could be fixed by installing poetry first in the Makefile

(I got this error)

```sh
.env) [bram@robocop-acs databallpy]$ make deps
poetry install --with docs
make: poetry: No such file or directory
make: *** [Makefile:29: deps] Error 127
```

**Comment by Swopper050** [comment]
As discussed in #132, `poetry` recommends installing it system-wide (https://python-poetry.org/docs/#installation)

As such, it makes most sense to just update the README to mention that a developer should install poetry first.

**Comment by Alek050** [comment]
Since this is already covered in the contribution.md: (https://github.com/Alek050/databallpy/blob/main/CONTRIBUTING.md), this issue will be closed
