### ISSUE TITLE
Make choice between np.datetime64 and pd.to_datetime objects (opta and tracab differ)

### ISSUE THREAD

**Issue by Alek050** [Alek050/databallpy#20]
in match.periods, tracab is with np.datetime64, opta with pd.to_datetime

**Comment by Prit2341** [comment]
Do you mind If I work on this issue??

**Comment by Prit2341** [comment]
There is no match.periods any where

**Comment by Alek050** [comment]
I was referencing to the develop branch, not the main branch. However, we just published the first version with utilities. Now you can see in `databallpy.match` the `Match` object with a `periods` attribute.
