### ISSUE TITLE
Error in parsing Opta F7 files with multiple `SoccerDocument` 

### ISSUE THREAD

**Issue by rdghe** [Alek050/databallpy#95]
I found that databallpy cannot parse (at least) the following matches: 
- 20220529AZvsVitesse2287009
- 20220522AZvsscHeerenveen2286600
- 20220522VitessevsFCUtrecht2286602

because the F7 XML files contain two `SoccerDocument` elements each.

The parsing of the team data in `_load_metadata` gets messed up because of this.

These are the **2nd legs** of the 2022 Dutch Conference League Play-off games, so not "regular matches".

I am not sure what the reason is why Opta employed this format, if you @Alek050 @DaanGro have any potential explanation please let me know. With what I've gathered so far, the best fix seems to just ignore the second `SoccerDocument` for the matches.

**Comment by DaanGro** [comment]
Thanks for noting this and pointing it out to us! Could you elaborate on what information is in both `SoccerDocument` elements? Are they both the exact same or is the second one corresponding to the 1st leg?

**Comment by rdghe** [comment]
Indeed the second one corresponds to the first leg:
```
<MatchInfo MatchType="1st Leg" Period="FullTime" TimeFrameLengthId="6" TimeStamp="20220529T152329+0100">
```
Whereas the first one is the second leg:
```
<MatchInfo MatchType="2nd Leg" Period="FullTime" PostMatch="1" TimeFrameLengthId="7" TimeStamp="20220529T152329+0100" Weather="Clear">
```

However, the first leg exists as a separate match (set of Opta F24 + F7). For example 20220526VitessevsAZ228700 for the first match I mentioned. In this XML there is only one `SoccerDocument` element.

Thus I think the second `SoccerDocument` in the 2nd leg matches files can be ignored.

**Comment by rdghe** [comment]
Sure, sounds good, I will open a PR later today :)

**Comment by rdghe** [comment]
done, see #98

**Comment by DaanGro** [comment]
Perfect, thanks!
