### ISSUE TITLE
Allow team formation of length 5

### ISSUE THREAD

**Issue by rdghe** [Alek050/databallpy#96]
As per the F7 XML file of  the `20220515AZvsRKCWaalwijk2207499` match (and not only), having a team formation of length 5 is possible in the Opta Events Metadata:
```
<TeamData Formation="41212" Score="3" Side="Away" TeamRef="t321">
```

The allowed length should be raised from 4 -> 5

**Comment by DaanGro** [comment]
I approved your pull request!
